keys:
  - &auxves age15k7x7umuau2ucnv09xcgr58s8vhz3tapr4rj0ah8j2r597shwelqfa60e0
  - &tide age130smjsmgjrxqjke8knxta9f2l34v3ucdjx9qf07rtw0aulx5e4kq8wdvrs
creation_rules:
  - path_regex: hosts/tide/.+
    key_groups:
      - age:
          - *auxves
          - *tide
