entryPoints:
  internal:
    address: :443
    asDefault: true

    http:
      tls:
        certResolver: letsencrypt

    http3: {}

  public:
    address: :8443

    http:
      tls:
        certResolver: letsencrypt

    http3: {}

certificatesResolvers:
  letsencrypt:
    acme:
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 9.9.9.9:53
      email: me@auxves.dev
      storage: /etc/traefik/acme.json

providers:
  docker:
    exposedByDefault: false

api:
  insecure: true

ping: {}

metrics:
  prometheus: {}

serversTransport:
  insecureSkipVerify: true
