on:
  push:

jobs:
  nixos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix Store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build `tide`
        run: nix run nixpkgs#nixos-rebuild -- build --flake .#tide
